# Site settings
email: your-email@domain.com
baseurl: ""
url: "http://yourdomain.com"

title: sample title
logo: /projects/2012/TeamA/img/logo.jpg
year: 2012
description: sample description
nrOfImages: 2
imgPath: /projects/2012/TeamA/img/


# Build settings
markdown: kramdown
permalink: pretty

