# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"

#default values or our databse
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "postTemplate"
      title: "sample title"
      logo: "/projects/2012/TeamA/img/logo.jpg"
      year: "2012"
      description: "sample description"
      nrOfImages: "2"
      imgPath: "/projects/2012/TeamA/img/"

# Build settings
markdown: kramdown
permalink: pretty

